name: Build and Test Android

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # تعيين إصدار Java إلى 11
        distribution: 'zulu'  # تحديد التوزيع المناسب لـ Java

    - name: Build with Gradle
      run: ./gradlew build
